global_frame: odom

rolling_window: true
publish_frequency: 2.0
planner_frequnecy: 5.0
planner_patientce: 5.0

# size of costmap is specified in robot folder

# plugins for local costmap are in robot folder
